require('./bootstrap');
require('./components/crud-handler');
require('./components/form-helper');
require('./components/auth');
require('./components/registration');
require('./components/save-winner.js');
require('./components/spinner-2');
require('./components/get');
// require('./components/spinner-1');
require('./components/modal');
require('./components/theme');
